In [1]:
import torch
from torch.utils.data import DataLoader, Dataset, SequentialSampler, RandomSampler,TensorDataset
from transformers import  RobertaConfig, RobertaModel, RobertaTokenizer
import argparse
import json
import os
from model2 import Model
from torch.utils.data import DataLoader, Dataset, SequentialSampler, RandomSampler,TensorDataset
import random
import multiprocessing
from tqdm import tqdm, trange
import numpy as np
import javalang
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
np.random.seed(0)
import seaborn as sns
import collections
import pickle
import sklearn
from matplotlib import cm
from sklearn import manifold
from syntaxType import SYNTAXTYPE

/Users/jirigesi/anaconda3/envs/CodeBert/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
class TextDataset(Dataset):
    def __init__(self, tokenizer, sample_size=1000, file_path='train', block_size=512,pool=None):
        postfix=file_path.split('/')[-1].split('.txt')[0]
        self.examples = []
        index_filename=file_path
        print("Creating features from index file at %s ", index_filename)
        url_to_code={}
        with open('/'.join(index_filename.split('/')[:-1])+'/data.jsonl') as f:
            for line in f:
                line=line.strip()
                js=json.loads(line)
                url_to_code[js['idx']]=js['func']
        data=[]
        cache={}
        f=open(index_filename)
        with open(index_filename) as f:
            for line in f:
                line=line.strip()
                url1,url2,label=line.split('\t')
                if url1 not in url_to_code or url2 not in url_to_code:
                    continue
                if label=='0':
                    label=0
                else:
                    label=1
                data.append((url1,url2,label,tokenizer,cache,url_to_code))
        data=data[:sample_size]

        self.examples=pool.map(get_example,tqdm(data,total=len(data)))
    def __len__(self):
        return len(self.examples)

    def __getitem__(self, item):
        return torch.tensor(self.examples[item].input_ids),torch.tensor(self.examples[item].label)


In [3]:
def get_example(item):
    url1,url2,label,tokenizer,cache,url_to_code=item
    if url1 in cache:
        code1=cache[url1].copy()
    else:
        try:
            code=' '.join(url_to_code[url1].split())
        except:
            code=""
        code1=tokenizer.tokenize(code)
    if url2 in cache:
        code2=cache[url2].copy()
    else:
        try:
            code=' '.join(url_to_code[url2].split())
        except:
            code=""
        code2=tokenizer.tokenize(code)
        
    return convert_examples_to_features(code1,code2,label,url1,url2,tokenizer,block_size, cache)

In [4]:
class InputFeatures(object):
    """A single training/test features for a example."""
    def __init__(self,
                 input_tokens,
                 input_ids,
                 label,
                 url1,
                 url2):
        self.input_tokens = input_tokens
        self.input_ids = input_ids
        self.label=label
        self.url1=url1
        self.url2=url2

In [5]:
def load_and_cache_examples(tokenizer, 
                            test_data_file,
                            block_size, 
                            sample_size=1000,
                            evaluate=False,
                            test=False,
                            pool=None):
    dataset = TextDataset(tokenizer, 
                          file_path=test_data_file,
                          sample_size=sample_size,
                          block_size=block_size,
                          pool=pool)
    return dataset

In [6]:
def convert_examples_to_features(code1_tokens,code2_tokens,label,url1,url2,tokenizer,block_size,cache):
    code1_tokens=code1_tokens[:block_size-2]
    code1_tokens =[tokenizer.cls_token]+code1_tokens+[tokenizer.sep_token]
    code2_tokens=code2_tokens[:block_size-2]
    code2_tokens =[tokenizer.cls_token]+code2_tokens+[tokenizer.sep_token]  
    
    code1_ids=tokenizer.convert_tokens_to_ids(code1_tokens)
    padding_length = block_size - len(code1_ids)
    code1_ids+=[tokenizer.pad_token_id]*padding_length
    
    code2_ids=tokenizer.convert_tokens_to_ids(code2_tokens)
    padding_length = block_size - len(code2_ids)
    code2_ids+=[tokenizer.pad_token_id]*padding_length
    
    source_tokens=code1_tokens+code2_tokens
    source_ids=code1_ids+code2_ids
    return InputFeatures(source_tokens,source_ids,label,url1,url2)

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

config = RobertaConfig.from_pretrained('microsoft/codebert-base')

tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

model = RobertaModel.from_pretrained('microsoft/codebert-base',
                                    output_attentions=True, 
                                    output_hidden_states=True)

model=Model(model,config,tokenizer)

model = model.to(device)

In [8]:
device

device(type='cpu')

In [8]:
file_path = "../dataset/valid.txt"
postfix=file_path.split('/')[-1].split('.txt')[0]
index_filename=file_path
url_to_code={}
with open('/'.join(index_filename.split('/')[:-1])+'/data.jsonl') as f:
    for line in f:
        line=line.strip()
        js=json.loads(line)
        url_to_code[js['idx']]=js['func']
data=[]
cache={}
f=open(index_filename)
with open(index_filename) as f:
    # lines = 1000
    added_lines = 0
    for line in f:
        # if added_lines >= lines:
        #     break
        line=line.strip()
        url1,url2,label=line.split('\t')
        if url1 not in url_to_code or url2 not in url_to_code:
            continue
        if label=='0':
            label=0
        else:
            label=1
        data.append((url1,url2,label,' '.join(url_to_code[url1].split()), ' '.join(url_to_code[url2].split())))
        added_lines += 1

In [9]:
len(data)

415416

In [11]:
data[0]

('13653451',
 '21955002',
 0,
 'public ViewInitListener() throws IOException { URL url = this.getClass().getResource(VIEW_INIT_CONFIG); log.debug("Loading configuration from: " + url); config = new Properties(); InputStream in = url.openStream(); config.load(in); in.close(); }',
 'public void run() { String s, s2; s = ""; s2 = ""; try { URL url = new URL("http://www.m-w.com/dictionary/" + Word); BufferedReader in = new BufferedReader(new InputStreamReader(url.openStream())); String str; while (((str = in.readLine()) != null) && (!stopped)) { s = s + str; } in.close(); } catch (MalformedURLException e) { } catch (IOException e) { } Pattern pattern = Pattern.compile("popWin\\\\(\'/cgi-bin/(.+?)\'", Pattern.CASE_INSENSITIVE | Pattern.DOTALL); Matcher matcher = pattern.matcher(s); if ((!stopped) && (matcher.find())) { String newurl = "http://m-w.com/cgi-bin/" + matcher.group(1); try { URL url2 = new URL(newurl); BufferedReader in2 = new BufferedReader(new InputStreamReader(url2.openStream(

In [10]:
def get_syntax_types_for_code(code_snippet):
  types = ["[CLS]"]
  code = ["<s>"]
  tree = list(javalang.tokenizer.tokenize(code_snippet))
  
  for i in tree:
    j = str(i)
    j = j.split(" ")
    if j[1] == '"MASK"':
      types.append('[MASK]')
      code.append('<mask>')
    else:
      types.append(j[0].lower())
      code.append(j[1][1:-1])
    
  types.append("[SEP]")
  code.append("</s>")
  return np.array(types), ' '.join(code)

In [14]:
block_size = 400

code_sample = data[0]
types_1, rewrote_code_1 = get_syntax_types_for_code(code_sample[3])

In [15]:
def convert_syntax_to_ids(syntax):
  type_ids = []
  for i in syntax:
    if i in SYNTAXTYPE.__members__:
      type_ids.append(SYNTAXTYPE[i].value)
    else: 
        type_ids.append(SYNTAXTYPE['unknown'].value)
  return type_ids

In [16]:
type_ids = convert_syntax_to_ids(types_1)

In [30]:
syntax_ids = torch.tensor(type_ids)

/var/folders/qy/62ts5q8x08j4g0wyry_tmbjm0000gn/T/ipykernel_13098/4278530770.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  syntax_ids = torch.tensor(type_ids)


In [28]:
if type_ids[1] == SYNTAXTYPE['modifier'].value: 
    print("1")
else:
    print("0")

1


In [25]:
type_ids

tensor([  0,  90,  70, 130, 130,  80,  70, 130,  70,  70, 120,  80, 130,  70,
        130, 130, 130,  70, 130,  70, 130, 130,  70, 130,  70, 130, 140, 120,
         70, 130, 130,  70, 120,  80,  70, 130, 130, 130,  70,  70, 120,  70,
        130,  70, 130, 130, 130,  70, 130,  70, 130,  70, 130, 130,  70, 130,
         70, 130, 130, 130, 130,   0])

In [31]:
attend_syntax_id = SYNTAXTYPE['modifier'].value

for i in range(len(syntax_ids)):
    if syntax_ids[i] == attend_syntax_id:
        print(i)

1


In [ ]:
tensor([[  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0],
        [  0, 130,   0]])

In [11]:
block_size = 400

code_sample = data[0]
types_1, rewrote_code_1 = get_syntax_types_for_code(code_sample[3])
types_2, rewrote_code_2 = get_syntax_types_for_code(code_sample[4])

tokenized_ids_1 = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(rewrote_code_1))
tokenized_ids_2 = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(rewrote_code_2))
if len(tokenized_ids_2) > block_size:
    tokenized_ids_2 = tokenized_ids_2[:block_size-1] + [tokenizer.sep_token_id]

if len(tokenized_ids_1) > block_size:
    tokenized_ids_1 = tokenized_ids_1[:block_size-1] + [tokenizer.sep_token_id]

padding_length = block_size - len(tokenized_ids_1)
tokenized_ids_1+=[tokenizer.pad_token_id]*padding_length
padding_length = block_size - len(tokenized_ids_2)
tokenized_ids_2+=[tokenizer.pad_token_id]*padding_length

source_ids = tokenized_ids_1 + tokenized_ids_2
labels = code_sample[2]
source_ids = torch.tensor(source_ids).unsqueeze(0).to(device)
labels = torch.tensor(labels).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(block_size,source_ids,labels)

In [20]:
a = output[-1]

In [25]:
attention = a.attentions

In [26]:
len(attention), attention[0].shape

(12, torch.Size([2, 12, 400, 400]))

In [27]:
attention[0].shape[-1]


400

In [19]:
output

(tensor(0.9178),
 tensor([[0.3994, 0.6006]]),
 BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.0355,  0.2179, -0.1205,  ..., -0.2351, -0.3512,  0.5136],
          [-0.6027, -0.1589,  0.7336,  ..., -0.1379, -0.0620,  0.4145],
          [-0.4189,  0.0220,  0.3724,  ...,  0.1358, -0.3719,  0.2697],
          ...,
          [ 0.0859,  0.2590,  0.2564,  ..., -0.1691, -0.1789,  0.1343],
          [ 0.0859,  0.2590,  0.2564,  ..., -0.1691, -0.1789,  0.1343],
          [ 0.0859,  0.2590,  0.2564,  ..., -0.1691, -0.1789,  0.1343]],
 
         [[ 0.1939,  0.1170, -0.1688,  ..., -0.1974, -0.2755,  0.3809],
          [-0.4745,  0.2696,  1.0089,  ..., -0.1244,  0.1960,  0.4228],
          [-0.1038, -0.0580,  1.2897,  ..., -1.5259, -0.6842,  0.2098],
          ...,
          [-0.2341, -0.4868,  0.2877,  ..., -0.4155, -0.3185,  1.1786],
          [-0.2863, -0.5097,  0.3295,  ..., -0.6609, -0.4961,  0.6529],
          [ 0.1934,  0.1198, -0.1688,  ..., -0.1981, -0.2787,  0.3

In [29]:
one_to_one = torch.eye(400)

In [32]:
one_to_one

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [31]:
one_to_one.shape

torch.Size([400, 400])

In [ ]:
def create_pos_attn_patterns(attentions):
    '''
    Creates attention patterns related to positional encoding for attention initialization
    one_to_one - pays attention to the corresponding token
    next_token - pays attention to the next token
    prev_token - pays attention to the previous token
    cls_token  - pays attention to the first index ([CLS])
    '''

    one_to_one = torch.eye(attentions[0].shape[-1])
    next_token = torch.cat((torch.cat((torch.zeros(attentions[0].shape[-1]-1, 1), torch.eye(attentions[0].shape[-1]-1)), dim=1),\
        torch.zeros(1, attentions[0].shape[-1])), dim=0)
    prev_token = torch.cat((torch.zeros(1, attentions[0].shape[-1]), \
        torch.cat((torch.eye(attentions[0].shape[-1]-1), torch.zeros(attentions[0].shape[-1]-1, 1)), dim=1)), dim=0)
    cls_token = torch.zeros(attentions[0].shape[-1], attentions[0].shape[-1])
    cls_token[:,0] = 1.

    return [one_to_one, next_token, prev_token, cls_token]   

In [ ]:
def compute_ag_loss(inputs, attentions, device, attn_head_types='0,1,1,4'):
        '''
        Adds a random loss based on attention values
        To test gradients
        outputs[-1] contains the attention values (tuple of size num_layers)
        and each elements is of the shape
        [batch_size X num_heads X max_sequence_len X max_sequence_len]
        '''
        # Get the attention head types
        attn_head_types = [int(i) for i in attn_head_types.split(',')]

        # The number attention heads of each type. one-to-one, next, previous, first
        numbers = attn_head_types
        print('numbers:', numbers)
        cum_sum = np.cumsum(numbers)
        print('cum_sum:', cum_sum)
        # Matrices containing the attention patterns
        targets = create_pos_attn_patterns(attentions)
        # Loss for positional attention patterns
        expanded_targets = []
        loss = torch.nn.MSELoss()
        total_loss = 0.        
        # Change the tensor's dimension
        for (num, target) in zip(numbers, targets):
            if num == 0:
                expanded_targets.append(None)
            else:
                # Add dimensions so that the tensor can be repeated
                target = torch.unsqueeze(target, 0)
                target = torch.unsqueeze(target, 0)
                # Change the target tensor's dimension so that it matches batch_size X num_heads[chosen]
                target = target.repeat(attentions[0].shape[0], num, 1, 1)
                target = target.to(device)
                expanded_targets.append(target)

        # Go over all the layers
        for i in range(len(attentions)):
            for j in range(len(numbers)):
                if expanded_targets[j] is not None:
                    if j == 0:
                        total_loss += loss(expanded_targets[j], attentions[i][:,0:cum_sum[j]])
                    else:
                        total_loss += loss(expanded_targets[j], attentions[i][:,cum_sum[j-1]:cum_sum[j]])
        return total_loss, targets, expanded_targets

In [ ]:
scale = 1
mlm_loss = output[0]
ag_loss, targets, expanded_targets = compute_ag_loss(source_ids, 
                                                     output[2].attentions, 
                                                     device, attn_head_types='0,1,1,4')

# loss = mlm_loss + ag_loss * scale * linear_schedule_for_scale()

In [ ]:
print('mlm_loss:', mlm_loss.item(), 'ag_loss:', ag_loss.item(), 'total_loss:', mlm_loss.item() + ag_loss.item() * scale)

In [ ]:
for i in range(0, len(targets)):
    try: 
        print(targets[i].shape, expanded_targets[i].shape)
    except Exception as e:
        print(e)

In [ ]:
attention = output[2].attentions
print('Number of layers:', len(attention))

# [batch_size X num_heads X max_sequence_len X max_sequence_len]
print('Each layer attention shape:', attention[0].shape)

In [52]:
# read the pickle files 
with open('/Users/jirigesi/Documents/icse2023/attentionBias/Clone-detection-BigCloneBench/code/attentions.pickle', 'rb') as f:
    attentions = pickle.load(f)

In [54]:
len(attentions), attentions[0].shape

(12, torch.Size([8, 12, 400, 400]))

In [55]:
with open('/Users/jirigesi/Documents/icse2023/attentionBias/Clone-detection-BigCloneBench/code/targets.pickle', 'rb') as f:
    targets = pickle.load(f)

In [59]:
len(targets), targets[0].shape, targets[1].shape

(2, torch.Size([400, 400]), torch.Size([8, 400, 400]))

In [61]:
targets[1].shape

torch.Size([8, 400, 400])

In [62]:
attentions[0].shape

torch.Size([8, 12, 400, 400])

In [63]:
loss = torch.nn.MSELoss()
total_loss = 0.  

In [78]:
target = torch.unsqueeze(targets[1], 0)

In [79]:
target.shape

torch.Size([1, 8, 400, 400])

In [81]:
target = target.repeat(12, 1, 1, 1)

In [82]:
target.shape

torch.Size([12, 8, 400, 400])

In [83]:
# change target from head*batch*seq*seq to batch*head*seq*seq
target = target.permute(1, 0, 2, 3)

In [84]:
target.shape

torch.Size([8, 12, 400, 400])

In [85]:
total_loss += loss(target, attentions[0][:,1:2])

/Users/jirigesi/anaconda3/envs/CodeBert/lib/python3.10/site-packages/torch/nn/modules/loss.py:529: UserWarning: Using a target size (torch.Size([8, 1, 400, 400])) that is different to the input size (torch.Size([8, 12, 400, 400])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [86]:
attentions[0].shape

torch.Size([8, 12, 400, 400])

In [87]:
total_loss

tensor(0.0034, grad_fn=<AddBackward0>)

In [89]:
attentions[0].shape[1]

12